language: r
sudo: false
cache: packages
r:
  - release
  - devel

r_github_packages:
   - hadley/dplyr
   - hannesmuehleisen/MonetDBLite-R

after_failure:
  - ./travis-tool.sh dump_logs

addons:
  apt_packages:
    - pandoc
