language: r
sudo: false
cache: packages
r:
  - release
  - devel

r_github_packages:
   - hadley/dplyr
   - hadley/dbplyr
   - hadley/dtplyr
   - Rdatatable/data.table

after_failure:
  - ./travis-tool.sh dump_logs

addons:
  apt_packages:
    - pandoc
